---
# tasks file for loadbalancer
#


  - name: Create Load Balancer
    ec2_elb_lb:
            name: "{{ LB_Name }}"
            state: present
            region: "{{ region }}"
            zones:
                - "{{ region }}a"
                - "{{ region }}c"
            listeners:
                    - protocol: http
                      load_balancer_port: 80
                      instance_port: 80
    register: elb

   

  - name: Add loadbalancer to EC2 security groups 
    ec2_group:
            name: "{{ sec_group }}"
            vpc_id: "{{ vpc_id }}"
            region: "{{ region }}"
            description: Allowing connections from loadbalancer
            rules:
                    - proto: tcp
                      from_port: 80
                      to_port: 80    
                      group_id: "{{ elb.elb.security_group_ids | first }}"
                    - proto: tcp
                      ports:
                           - 80
                      cidr_ip: 0.0.0.0/0
                      rule_desc: allow all on port 8080
                    - proto: tcp
                      ports: 
                        - 22
                      cidr_ip: "{{ ansible_master_ip.content | replace('\n', '') }}/32"  
                      rule_desc: allow ssh connection from ansible master to perform tasks
  



  - name: Get EC2 instance details
    ec2_instance_facts:
            region: "{{ region }}"    
            filters:
                   "tag:Name": Webserver  
    register:  ec2_details         

  - debug:
              msg: "{{ item.instance_id }}"
    with_items:          
           - "{{ ec2_details.instances }}"


  - name: Attach instances to the loadbalancer
    ec2_elb:
              ec2_elbs: "{{ LB_Name }}"
              region: "{{ region }}"
              state: present
              instance_id: "{{ item.instance_id }}"
    with_items:      
               - "{{ ec2_details.instances }}"

